# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e0bf61ae77e0f04b3bdb9eb3458a86aad400b00e752fe574187ad5d6dc4003ea8134e1e837cf697c4454e8ca9db9dd1b2c8301e3479ac42583302e15776dd14

test:
  secret_key_base: 915790cbea63ec5cb63a588801420ee94f8b1fb51b748e65d01273b157566069c8ae2dda61e9e43e0f4b9b5d737be7f565958f9bd321b3087ec4362890ff077f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
